name: Plugin asset/readme update
on:
  push:
    tags:
    - "*"
jobs:
  tags:
    name: Push Assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        IGNORE_OTHER_FILES: true
        SLUG: fac-hosted-page-button